services:
  # --------------------------------
  db:
    image: postgis/postgis:13-3.1
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  # --------------------------------
  api:
    build:
      context: ./
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_S3_BUCKET=castle-data-develop
      - AWS_S3_ENDPOINT=http://minio:9000
      - AWS_S3_DISABLE_SSL=True
      - AWS_S3_FORCE_PATH_STYLE=True
      - AUTH_MOCKED=true
      - APPLICATION_KEY=appkey
      - WORKFORCE_DB_USER=workforce_user
      - WORKFORCE_DB_PASS=workforce_pass
      - WORKFORCE_DB_NAME=postgres
      - WORKFORCE_DB_HOST=db
      - WORKFORCE_DB_SSLMODE=disable
      - DB_POOL_MAX_CONNS=10
      - DB_POOL_MAX_CONN_IDLE_TIME=30m
      - DB_POOL_MIN_CONNS=5
    ports:
      - '80:80'
    depends_on:
      - db
  # --------------------------------
  flyway:
    image: flyway/flyway
    restart: on-failure
    command: -url=jdbc:postgresql://db:5432/postgres -schemas=workforce -user=postgres -password=postgres -connectRetries=60 migrate
    environment:
      - FLYWAY_EDITION=community
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql/common,filesystem:/flyway/sql/develop,filesystem:/flyway/sql/local
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - db
  # --------------------------------
