# The parser will ignore extension fields prefixed with 'x-'

# **********************************************************************
# setup allowing debug
# use target: development and command: with dlv debug
# **********************************************************************
x-common:
  build: &build
    dockerfile: Dockerfile
    target: development
  command: &command dlv debug /go/src/api --accept-multiclient --headless --listen ":2345" --continue
  # command: &command '/go/bin/api' # command if no target

services:
  # --------------------------------
  db:
    image: postgis/postgis:13-3.1
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  # --------------------------------
  api:
    build:
      context: ./api
    restart: always
    environment:
      AUTH_MOCKED: true
      AUTH_ENVIRONMENT: DEVELOP
      WORKFORCE_DB_USER: workforce_user
      WORKFORCE_DB_PASS: workforce_pass
      WORKFORCE_DB_NAME: postgres
      WORKFORCE_DB_HOST: db
      WORKFORCE_DB_SSL_MODE: disable
      DB_POOL_MAX_CONNS: 10
      DB_POOL_MAX_CONN_IDLE_TIME: 30m
      DB_POOL_MIN_CONNS: 5
    ports:
      - '80:80'
      - '2345:2345'
    volumes:
      - ./api/:/go/src/app/:rw
    depends_on:
      - db
  # --------------------------------
  flyway:
    image: flyway/flyway
    restart: on-failure
    command: "-connectRetries=60 migrate"
    environment:
      FLYWAY_EDITION: community
      FLYWAY_LOCATIONS: filesystem:/flyway/sql/common,filesystem:/flyway/sql/develop,filesystem:/flyway/sql/local
      FLYWAY_PASSWORD: postgres
      FLYWAY_SCHEMAS: workforce
      FLYWAY_URL: jdbc:postgresql://db:5432/postgres
      FLYWAY_USER: postgres
      FLYWAY_VALIDATE_MIGRATION_NAMING: true
      FLYWAY_PLACEHOLDERS_APP_PASSWORD: workforce_pass
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - db
  # --------------------------------
